#!/usr/bin/env python3
##
## EPITECH PROJECT, 2019
## 204ducks_2018
## File description:
## 204ducks
##

from sys import argv
from utilities import usage, error
from proba import get_avg_time, duck_return, get_proba, get_standard_dev

def display(data: float) -> None:
    """Displays results."""
    print('Average return time: {0[0]}m {0[1]}s'
        .format(get_avg_time(data)),
        'Standard deviation: {:.03f}'
        .format(get_standard_dev(data, get_avg_time(data, 1))),
        'Time after which 50% of the ducks are back: {0[0]}m {0[1]}{0[2]}s'
        .format(duck_return(0.5, data)),
        'Time after which 99% of the ducks are back: {0[0]}m {0[1]}{0[2]}s'
        .format(duck_return(0.99, data)),
        'Percentage of ducks back after 1 minute: {:.01f}%'
        .format((get_proba(data, 1) - get_proba(data, 0)) * 100),
        'Percentage of ducks back after 2 minutes: {:.01f}%'
        .format((get_proba(data, 2) - get_proba(data, 0)) * 100),
        sep='\n')

def ducks(data: float) -> None:
    """204ducks main function."""
    if data >= 0 and data <= 2.5:
        display(data)
    else:
        error('\'a\' must be a float constant between 0 and 2.5.\n')

if __name__ == "__main__":
    if len(argv) != 2:
        error('Invalid number of arguments, type \'-h\' for more informations.\n')
    elif len(argv) == 2 and argv[1] == "-h":
        usage()
    else:
        try:
            data = float(argv[1])
        except:
            error('\'a\' must be a float. \'-h\' for more informations.\n')
        ducks(data)
